### ISSUE TITLE
No module named 'util'   You can provide util.py

### ISSUE THREAD

**Issue by Deep-learning999** [MohamedElashri/AI-for-Medical-Treatment#1]
![Screenshot_20200822_165320](https://user-images.githubusercontent.com/64831773/90952666-0b104900-e498-11ea-81b3-3731b24a579a.jpg)

**Comment by MohamedElashri** [comment]
Hello, you should be able to run this on the coursera course as they provide all files for grading in their workspace. 
util will provide the locally defined utility functions that have been provided for this assignment
However, I added the [file](https://github.com/MohamedElashri/AI-for-Medical-Treatment/blob/master/util.py) if you want to run code locally.
